version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: LittleThings2*
      MYSQL_DATABASE: microfinance
    ports:
      - "3307:3306"
    networks:
      - springboot-net

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/microfinance
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: LittleThings2*
    networks:
      - springboot-net

networks:
  springboot-net:
